### ISSUE TITLE
Fix text editor paragraph breaks in commentaries

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#10]
Fix text editor bug in commentaries that makes a long commentary display as one, continuous block of text with no paragraph breaks:
http://www.criticalcommons.org/Members/DawnFratini/clips/caged-heat-and-the-women-in-prison-genre

**Comment by ahelme** [comment]
Hmmm... however I think this is related to the ticket regarding stripping commentaries of HTML tags, I suppose...

https://huboard.com/plumi/criticalcommons.content/#/milestones/issues/105998728

It is possible to make commentaries rich-text format, instead of plain text or HTML?

This way - spam could be prevented, but paragraph and line breaks could be allowed....?

**Comment by Ironman28** [comment]
Yes, please! That sounds perfect! And yes, I suspect this is related to #27 about commentary spam.

**Comment by mgogoulos** [comment]
closing
