### ISSUE TITLE
RSS feed missing media file URLs

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#29]
From our Scalar partner developer - this is important for being able to import CC videos into Scalar!

In the Critical Commons Atom feed, some of the media file URLs are missing. For example, here is the URL to the feed we use when searching for 'simpsons':

http://criticalcommons.org/cc/playlist?SearchableText=simpsons

Depending on your browser, you may need to View > Source to see the XML source (as opposed to a rendering of it, since this format is used for RSS).  Once you can see the XML, run a string search (Option-F) for "none/none", and you'll see two nodes that have this:
<link>None/None</link>

This should instead have a URL to the media file in it, for example (from another node in the same document):
<link>http://videos.criticalcommons.org/transcoded/http/www.criticalcommons.org/Members/AdrianFohr/clips/elasticity-necessity-or-luxury/video_file/mp4-high/elasticity-in-the-simpsons-m4v.mp4</link>

**Comment by ahelme** [comment]
Hmmm.

One of those "none"links was related to a video from this user:
http://www.criticalcommons.org/Members/gdmateer/clips/?b_start:int=0

Why are all his clips private?? Because they have no commentaries?

SO - I assume that the clips don't have a link because they are in fact, private?

Eg
http://www.criticalcommons.org/Members/gdmateer/clips/simpsons_mr_plow_final.m4v

SO - do we have to change the feed to NOT include private videos?

Or Steve - does Scalar want access to private videos??

**Comment by Ironman28** [comment]
Right. The feed should NOT include private videos (if that's possible), only published ones. 
(Dirk Mateer has hundreds of Economics clips that were retracted under pressure from his publisher)

**Comment by Ironman28** [comment]
Closing. Opening new ticket to prevent private videos from appearing in RSS feed.
