### ISSUE TITLE
Embedded videos blocked by new browser security?

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#31]
I just received this note from a user, who has dozens of embedded clips that have all broken! Here is an example: http://yadayadayadaecon.com/clip/20/ Can this be fixed? Why isn't this an issue for other embeds?

"I run a site called "The Economics of Seinfeld". We embed Critical Commons videos on our own web site. Recently, I suspect due to browser security changes, the embedding stopped working. The problem appears to be that your server is setting the 'X-Frame-Options' HTTP header to 'SAMEORIGIN', which now causes modern browsers to block the content. I believe that the solution is for your server to stop setting that header on embed URLs."

**Comment by ahelme** [comment]
Will have to leave this to Markos, I'm not sure what advice to offer...

**Comment by Ironman28** [comment]
Ack! I just noticed that CC videos are blocked from my very own WordPress site! Here is an example: 
http://technocinema.net/post/61794245008/humans-vs-mainframe-computers-on-film-and-tv

**Comment by ahelme** [comment]
(presumably all embedded videos?)

**Comment by ahelme** [comment]
Actually... it's a shame (for selfish reasons) as I wanted to include the trailer for my film MyMy, hosted on Critical Commons, in a paper I'm getting published in a University of Melbourne School of Culture and Communications online journal (Platform) special edition commemorating 30 years since Donna Haraway's A Cyborg Manifesto.. CC seemed a very appropriate place, and I wanted to do a little plug of CC to Australian cyber-friendly academics (and then link back to my paper from the trailer on CC via a commentary). I do think cinema studies departments that don't use CC (or something like it) are nuts, personally, it's such a good idea! Well, just technophobic I guess...

http://www.criticalcommons.org/Members/anna/clips/mymy-trailer

But I will have to give them the Vimeo embed instead I guess, as I don't think the CC embed will appear?

(of course, my personal concerns here are not at all important, just thought I'd mention it!)

**Comment by Ironman28** [comment]
I think we should escalate this ticket to top priority! I just got another message from a user saying that all his videos are blocked and unplayable! He attributes this to having "X-Frame-Options Set to SAMEORIGIN"
++++
I'm one of the people involved in the http://bazinganomics.com site.  This morning, we noticed that you've changed a setting on your shared videos: you've set the X-Frame-Options Set to SAMEORIGIN.  That setting makes it impossible to embed content on external sites.  Was this intentional?

Thanks!

Ben Smith
Assistant Professor
University of Nebraska at Omaha

**Comment by mgogoulos** [comment]
trying to debug this issue

**Comment by mgogoulos** [comment]
I've removed that X-Frame-Options and videos are served correctly now. Please let the people that noticed this issue know that is is fixed. 

Also, I've set the fix on engagemedia.org (which was also not serving embedded videos) due to this.

**Comment by Ironman28** [comment]
Bam! Thank you, Markos! Closing.

**Comment by ahelme** [comment]
Markos, thank you!!!

EM had not let me know of any issue at all. I'll email them now to let them know you fixed this!
