### ISSUE TITLE
Change "Resources" page to "How To"

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#33]
The Resources page http://www.criticalcommons.org/blog/resources is a mess right now - I never update it, the layout is terrible and the materials are not what users most need. I think we should change this page to "How To" and make it a space for instructing new users in how to use Critical Commons. Ideally, this would be a combination of text (compression and format recommendations, fair use resources, etc.) and possibly a video tutorial on creating an account and uploading a video. This video does not currently exist, but I could make one. For now, would it be possible to rename this page and make it so it can accommodate these materials?

**Comment by ahelme** [comment]
I will test this today, to find out what content type this page is.

**Comment by ahelme** [comment]
Hi Steve - that page is a collection, so rather than renaming it and re-purposing it, I have created a new page here, called How To, in the root directory:

http://www.criticalcommons.org/how-to

If you want to edit this page, perhaps later Markos could:
- change link in CC skin top menu entitled Resources to be called How To, and direct to the link above.

For now - do you want to add some content to this page?

For compression, you could use this page that I wrote for EngageMedia as a guide:
http://www.engagemedia.org/help/how-to-compress-video

Or reference Vimeo's here:
https://vimeo.com/help/compression

**Comment by Ironman28** [comment]
Done. Let's please simply remove the "Resources" link from the main navigation bar.

**Comment by mgogoulos** [comment]
I agree, much cleaner now, once the how to page is updated we can link in on the header menu

**Comment by mgogoulos** [comment]
actually just noted that how to is already on the header menu. Would you like to remove it for now, or is it ok to be there?

**Comment by Ironman28** [comment]
I thought _you_ put the How To link in the Header! It would be nice if "How To" could be moved over to the 3rd position from the left, like this: Home, Browse, How To, [Upload], Lectures, About, Contact

**Comment by Ironman28** [comment]
Closing. Creating new ticket to move How To link to different position in header nav bar
