### ISSUE TITLE
Overwhelmed by spam since changes to Advanced User registration

### ISSUE THREAD

**Issue by Ironman28** [plumi/criticalcommons.content#46]
I used to get ONE attempt at a spam account  every 1-2 MONTHS. For the last couple of weeks, I have been getting 3-4 attempts EVERY HOUR, which is making me crazy. Is there any reason this might be happening because of a change in the registration process? All we did was make some fields mandatory and change the fields that are exposed by the Status drop-down menu, right? I know our sprint is already over, but is there any way to stop this? 

Here is an example spam application for Advanced User status: 

From: aureliagruber@spambog.com
Subject: User: Louise requested advanced status
Date: October 27, 2015 8:07:11 AM PDT
To: plumi.usc@gmail.com

LDXLouise5 of Metcalf and Beaudry mbH , is applying for Advanced User status in Critical Commons.

Home page URL is http://xn--xhq521b21ah86b.com/home.php?mod=space&uid=231305&do=profile&from=space, Username is Louise, and email address is aureliagruber@spambog.com.

**Comment by mgogoulos** [comment]
This is very strange, the functionality to apply for advanced user was there before, we have just hidden some fields (url/bio etc) that will only appear if advanced user selected, but in any case they are required. So the spammers have to provide them otherwise the request is not made. Cannot think how this has resulted in the form being more spam friendly though!

Since you use gmail, you could create a filter for messages that contain text "requested advanced status" in subject, to be archived on a folder. You would then have to visit that folder and allow the real users. Other solutions would include a captcha on the form (needs some work and would make the form less attractive, but most probably would prevent the big majority of spam users). Is this still an issue btw?

**Comment by mgogoulos** [comment]
I believe we are fine after captcha has been enabled, Steve?

**Comment by Ironman28** [comment]
Yes, the number of spam applications has dropped _almost_ to zero. Maybe one a week slips through. Thank you, Markos!
